### PR TITLE
Poster setup

### PR DESCRIPTION
**Pull request by omelkonian**
A very simple Latex setup for our poster. We will consider styling when we have the content. 
Let me know if you find the shaping/structuring totally displeasing, and I will find something more fancy.

### CODE REVIEW

**Comment by omelkonian** [comment]
I've added my part.
* Do not worry if your things go outside the borders; we will sort positioning when everyone has submitted their part.
* IMO styling looks quite ok atm, but we can review it before submission.

**Comment by joristt** [comment]
It feels a bit weird that everything is written in we-form, e.g. we don't report semantic errors, Hanus does.

**Comment by omelkonian** [comment]
true dat

**Comment by joristt** [comment]
You know what, I'll just accept it for now, we'll see how it turns out once all segments are written.

**Pull request merged**
