### PR TITLE
Poster: final styling and UU logo

### PR DESCRIPTION
**Pull request by omelkonian**

### CODE REVIEW

**Comment by omelkonian** [comment]
@jorisburgers I renamed `reverse_divide` to `divide'` to make up room for scaling up. Is that OK with you?

**Comment by jorisburgers** [comment]
@omelkonian That's fine with my, no problem

**Comment by omelkonian** [comment]
If everyone is OK with this version, @jorisburgers can merge and submit it to Wouter (as our usual representative :) )

**Comment by joristt** [comment]
I was looking at the colors a bit

**Comment by omelkonian** [comment]
@joristt I took the palette from here: https://wiki.haskell.org/Brand

**Comment by joristt** [comment]
Okay, I hate designing too much to put any time into this. @jorisburgers you can merge it.

**Comment by jorisburgers** [comment]
@joristt @omelkonian Is it possible to change the poster a little bit that the bottom two blocks align, there is a slight difference in their heights that is very noticeable once you see it.

**Comment by omelkonian** [comment]
@jorisburgers Ready to ship! :shipit:

**Comment by jorisburgers** [comment]
@omelkonian Thanks, I will merge and ship it

**Pull request merged**
